name: Auto Config Collector (3H)

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run collector
        run: python main.py
        
      - name: Copy outputs to docs
        run: |
          rm -rf docs/outputs
          mkdir -p docs/outputs
          cp -r outputs/* docs/outputs/
          cp outputs/subscribe_qr.png docs/outputs/

      - name: Debug outputs
        run: |
          echo "=== outputs ==="
          ls -lah outputs


      - name: Commit outputs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add outputs
          git commit -m "update collected configs" || echo "No changes"
          git push
